### ISSUE TITLE
asciidoctor.convert() leads to Opal Crash 

### ISSUE THREAD

**Issue by flobilosaurus** [asciidoctor/opal-node-runtime#132]
Hi, im the maintainer of the [asciidoc slides vscode extension](https://github.com/flobilosaurus/vscode-asciidoc-slides) which depends on @asciidoctor/core@2.2.5, which depends on asciidoctor-opal-runtime@0.0.33. and when i try to convert a document by
```typescript
asciidoctor.convert(asciidocText, { safe: 'safe', backend: 'revealjs', attributes: { docDir: this.absoluteDocumentDirectory } });
```
I get the following error message: 
```
rejected promise not handled within 1 second: TypeError: converter.$== is not a function
```

Here is the full stack trace:
```
stack trace: TypeError: converter.$== is not a function
	at /Users/florianl/Documents/Repositories/github/vscode-asciidoc-slides/dist/extension.js:26067:74
	at constructor.$$initialize (/Users/florianl/Documents/Repositories/github/vscode-asciidoc-slides/dist/extension.js:26071:24)
	at Object.send (/Users/florianl/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/asciidoctor-opal-runtime/src/opal.js:1671:19)
	at Function.$Class_new$5 (/Users/florianl/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/asciidoctor-opal-runtime/src/opal.js:3638:12)
	at Function.$$create (/Users/florianl/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:7226:37)
	at constructor.$$create_converter (/Users/florianl/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:8743:78)
	at constructor.$$update_backend_attributes (/Users/florianl/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:8996:97)
	at constructor.$$initialize (/Users/florianl/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:7875:16)
	at Object.send (/Users/florianl/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/asciidoctor-opal-runtime/src/opal.js:1671:19)
	at Function.$Class_new$5 (/Users/florianl/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/asciidoctor-opal-runtime/src/opal.js:3638:12)
	at /Users/florianl/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:16262:45
	at Function.$$load (/Users/florianl/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:16263:28)
	at Function.$$convert (/Users/florianl/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:16404:20)
	at Function.convert (/Users/florianl/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:21890:21)
	at RevealSlides.convertToRevealJsSlides (/Users/florianl/Documents/Repositories/github/vscode-asciidoc-slides/dist/extension.js:135556:28)
	at new RevealSlides (/Users/florianl/Documents/Repositories/github/vscode-asciidoc-slides/dist/extension.js:135552:32)
	at new Container (/Users/florianl/Documents/Repositories/github/vscode-asciidoc-slides/dist/extension.js:135239:29)
	at ContainerManager.getOrCreateContainer (/Users/florianl/Documents/Repositories/github/vscode-asciidoc-slides/dist/extension.js:135371:62)
	at ContainerManager.<anonymous> (/Users/florianl/Documents/Repositories/github/vscode-asciidoc-slides/dist/extension.js:135360:44)
	at Generator.next (<anonymous>)
	at /Users/florianl/Documents/Repositories/github/vscode-asciidoc-slides/dist/extension.js:135343:71
	at new Promise (<anonymous>)
	at /Users/florianl/Documents/Repositories/github/vscode-asciidoc-slides/dist/extension.js:135339:12
	at Object.andDo (/Users/florianl/Documents/Repositories/github/vscode-asciidoc-slides/dist/extension.js:135357:32)
	at Object.showPreview (/Users/florianl/Documents/Repositories/github/vscode-asciidoc-slides/dist/extension.js:135771:42)
	at /Users/florianl/Documents/Repositories/github/vscode-asciidoc-slides/dist/extension.js:135803:110
	at l._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:111652)
	at l.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:112090)
	at i._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13802)
	at i._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13486)
	at i._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:12148)
	at i._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:10826)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:8922
	at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15990)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:30514
	at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15990)
	at u._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21260)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:18138
	at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at w.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:13351)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:12699
	at Socket.v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:13465)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
	at Pipe.callbackTrampoline (internal/async_hooks.js:131:14)
```

This error seams to appear since vscode version >= 1.61.2 and did not appear before.
Is it a misconfiguration on my side or may be a bug on your side?

**Comment by ggrossetie** [comment]
> Is it a misconfiguration on my side or may be a bug on your side?

Neither, I think it's an incompatibility issue between how VS Code packages extensions and how Opal should be initialized.

You should try to create a simple/dummy extension that uses Asciidoctor.js to reproduce this issue. That would allow us to take a look at the generated code (`dist/extension.js`) to understand what workarounds we could use.

You can also debug the code step-by-step to understand why the `converter` object is not correctly initialized by Opal.

**Comment by flobilosaurus** [comment]
Thank you @Mogztter, i created a simple extension with asciidoctor and @asciidoctor/reveal.js packages. It seems that source of the bug is the @asciidoctor/reveal.js library containing the converter. I will try to contact devs of this library...

**Comment by flobilosaurus** [comment]
Fixed via https://github.com/asciidoctor/asciidoctor.js/issues/1475
